import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('electronAPI', {
  openExternal: (url: string) => ipcRenderer.invoke('open-external', url),
  networkPing: (host: string) => ipcRenderer.invoke('network-ping', host),
  networkIpConfig: () => ipcRenderer.invoke('network-ipconfig'),
  networkFlushDns: () => ipcRenderer.invoke('network-flush-dns'),
  networkReleaseIp: () => ipcRenderer.invoke('network-release-ip'),
  networkRenewIp: () => ipcRenderer.invoke('network-renew-ip'),
  networkReset: () => ipcRenderer.invoke('network-reset'),
  networkWinsockReset: () => ipcRenderer.invoke('network-winsock-reset'),
  networkRemoteDesktop: () => ipcRenderer.invoke('network-remote-desktop'),
  networkEnableTelnet: () => ipcRenderer.invoke('network-enable-telnet'),
  networkDisableTelnet: () => ipcRenderer.invoke('network-disable-telnet'),
  sfcScan: () => ipcRenderer.invoke('sfc-scan'),
  dismCheckHealth: () => ipcRenderer.invoke('dism-check-health'),
  dismScanHealth: () => ipcRenderer.invoke('dism-scan-health'),
  dismRestoreHealth: () => ipcRenderer.invoke('dism-restore-health'),
  checkDisk: () => ipcRenderer.invoke('check-disk'),
  windowsMemoryDiagnostic: () => ipcRenderer.invoke('windows-memory-diagnostic'),
  directxDiagnostic: () => ipcRenderer.invoke('directx-diagnostic'),
  fixWindowsApps: () => ipcRenderer.invoke('fix-windows-apps'),
  fixBluetooth: () => ipcRenderer.invoke('fix-bluetooth'),
  fixAudio: () => ipcRenderer.invoke('fix-audio'),
  troubleshootBluetooth: () => ipcRenderer.invoke('troubleshoot-bluetooth'),
  troubleshootCamera: () => ipcRenderer.invoke('troubleshoot-camera'),
  troubleshootNetwork: () => ipcRenderer.invoke('troubleshoot-network'),
  troubleshootPrinter: () => ipcRenderer.invoke('troubleshoot-printer'),
  troubleshootCompatibility: () => ipcRenderer.invoke('troubleshoot-compatibility'),
  troubleshootVideoPlayback: () => ipcRenderer.invoke('troubleshoot-video-playback'),
  troubleshootWindowsMediaPlayer: () => ipcRenderer.invoke('troubleshoot-windows-media-player'),
  troubleshootWindowsUpdate: () => ipcRenderer.invoke('troubleshoot-windows-update'),
  enableQuickRecovery: () => ipcRenderer.invoke('enable-quick-recovery'),
  disableQuickRecovery: () => ipcRenderer.invoke('disable-quick-recovery'),
  activateSelfHealing: () => ipcRenderer.invoke('activate-self-healing'),
  generateSystemLogs: () => ipcRenderer.invoke('generate-system-logs'),
  generateApplicationLogs: () => ipcRenderer.invoke('generate-application-logs'),
  generateSecurityLogs: () => ipcRenderer.invoke('generate-security-logs'),
  deleteRunHistory: () => ipcRenderer.invoke('delete-run-history'),
  deleteTempInternetFiles: () => ipcRenderer.invoke('delete-temp-internet-files'),
  clearWindowsUpdateCache: () => ipcRenderer.invoke('clear-windows-update-cache'),
  clearThumbnailCache: () => ipcRenderer.invoke('clear-thumbnail-cache'),
  clearMicrosoftStoreCache: () => ipcRenderer.invoke('clear-microsoft-store-cache'),
  clearOutlookCache: () => ipcRenderer.invoke('clear-outlook-cache'),
  clearTeamsCache: () => ipcRenderer.invoke('clear-teams-cache'),
  clearRecycleBin: () => ipcRenderer.invoke('clear-recycle-bin'),
  deleteOldWindows: () => ipcRenderer.invoke('delete-old-windows'),
  defragmentDrive: () => ipcRenderer.invoke('defragment-drive'),
  wipeFreeSpace: () => ipcRenderer.invoke('wipe-free-space'),
  manageDiskPartitions: () => ipcRenderer.invoke('manage-disk-partitions'),
  deleteRecentItems: () => ipcRenderer.invoke('delete-recent-items'),
  deleteAddressBarHistory: () => ipcRenderer.invoke('delete-address-bar-history'),
  checkIobitInstalled: () => ipcRenderer.invoke('check-iobit-installed'),
  getFileLockingProcesses: (targetPath: string) => ipcRenderer.invoke('get-file-locking-processes', targetPath),
  unlockFileNative: (targetPath: string, actionType: 'unlock' | 'delete' | 'rename' | 'move' | 'copy', actionArgs?: any) => 
    ipcRenderer.invoke('unlock-file-native', targetPath, actionType, actionArgs),
  unlockFileIobit: (targetPath: string, actionType: 'unlock' | 'delete' | 'rename' | 'move' | 'copy', modifier: 'normal' | 'advanced', actionArgs?: any) => 
    ipcRenderer.invoke('unlock-file-iobit', targetPath, actionType, modifier, actionArgs),
  selectFileDialog: () => ipcRenderer.invoke('select-file-dialog'),
  selectFolderDialog: () => ipcRenderer.invoke('select-folder-dialog'),
  scanBrowserExtensions: () => ipcRenderer.invoke('scanBrowserExtensions'),
  disableBrowserExtension: (id: string, browser: 'chrome' | 'edge' | 'firefox') => ipcRenderer.invoke('disableBrowserExtension', id, browser),
  removeBrowserExtension: (id: string, browser: 'chrome' | 'edge' | 'firefox') => ipcRenderer.invoke('removeBrowserExtension', id, browser),
  uninstallerScanExe: (exePath: string) => ipcRenderer.invoke('uninstaller-scan-exe', exePath),
  uninstallerDelete: (filePaths: string[], registryPaths: string[]) => ipcRenderer.invoke('uninstaller-delete', filePaths, registryPaths),
})
